# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 85ad2c475994d183cbc0ca629b05f469ec0c84945a723da98fa39f8f3d857f71e503ce7264919ef8e9b060612ca46a679e0f64bb69faa18c9878f4f13f89abbf

test:
  secret_key_base: 58824eb54bfd37a11dd465ec2df78359bbdb800ee867702deec6e6b53270cd304dd5bb56005d5a9d943e628ea6e73180b3e6c8f11bf2b455396788a9c6255581

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
